### ISSUE TITLE
openjournals/joss-reviews#4590 Community Guidelines

### ISSUE THREAD

**Issue by tokuso2** [ajohnson-uoregon/llvm-project#1]
If not already present, please add:
Guidelines for third parties wishing to 
    1) Contribute to the software 
    2) Report issues or problems with the software 
    3) Seek support

Apologies if it's already present and I just missed it (or if it's implicit)

**Comment by ajohnson-uoregon** [comment]
Added a bit to the readme: 908ddafb0975 and [70e18983](https://github.com/ajohnson-uoregon/clang-rewrite-only/commit/70e189833b53bf8e62bc6cb9054137b875a0e00f).
